name: PR Docs Build Check (Preview)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Show repo tree (pre-build)
        run: |
          pwd
          ls -la
          echo "---- docs/ ----"
          ls -la docs || true
          echo "---- find any docfx.json ----"
          find . -maxdepth 5 -name "docfx.json" -print

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install DocFX
        run: |
          dotnet tool install -g docfx
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Make sure we start from a clean output dir
      - name: Clean previous site
        run: |
          rm -rf docs/.site
          mkdir -p docs/.site

      # Build from your docfx root
      # (Assumes docs/site-src/docfx.json has "output": "../.site")
      - name: Build Docs
        working-directory: docs/site-src
        run: docfx docfx.json

      # Prove the site actually exists and has an index.html
      - name: Inspect built site
        run: |
          echo "---- docs/.site (post-build) ----"
          ls -la docs/.site || true
          echo "---- sample tree ----"
          find docs/.site -maxdepth 2 -type f | head -n 50
          test -f docs/.site/index.html || (echo "❌ No docs/.site/index.html found. Check your docfx.json output path." && exit 1)

      - name: Upload Preview Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docfx-preview
          path: docs/.site/**   # <- match actual files, not just the folder
