name: PR Docs Build Check (Preview)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install DocFX
        run: |
          dotnet tool install -g docfx
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # If your docfx.json is in docs/, build from there:
      - name: Build Docs
        working-directory: docs/site-src
        run: docfx docfx.json

      - name: Show repo tree (top level)
        run: |
          pwd
          ls -la
          echo "---- try to show docs/ ----"
          ls -la docs || true
          echo "---- find any docfx.json ----"
          find . -maxdepth 4 -name "docfx.json" -print

      - name: Upload Preview Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docfx-preview
          path: docs/.site
