name: Publish distributions on tag

on:
  push:
    branches:
      - main
    tags:
      - 'v*'   # e.g. v1.3.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: python -m pip install --upgrade pip build twine

      - name: Build Python distributions
        run: python -m build --sdist --wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Pack NuGet package
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          dotnet pack explorer-game/explorer-game.csproj -c Release -o nupkgs /p:PackageVersion="$VERSION"

      - name: Publish NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "nupkgs/*.nupkg" -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json
